name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: actions/upload-artifact@master
        with:
          name: parcel-artifacts
          path: dist/
# TODO: Add once tests are written
#  test:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - uses: actions/checkout@master
#      - name: Setup Node
#        uses: actions/setup-node@master
#        with:
#          node-version: '16.x'
#      - uses: actions/download-artifact@master
#        with:
#          name: parcel-artifacts
#          path: dist/
#      - uses: borales/actions-yarn@v2.3.0
#        with:
#          cmd: install
#      - uses: borales/actions-yarn@v2.3.0
#        with:
#          cmd: test
