name: Build and Test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Packages
        run: npm install
      - name: Build with Parcel
        run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: parcel-artifacts
          path: dist/
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - uses: actions/download-artifact@master
        with:
          name: parcel-artifacts
          path: dist/
      - name: Install Packages
        run: npm install
      - name: Run Tests
        run: npm test
        env:
          CI: true
