name: Publish Package
on:
  push:
    tags:
      - "*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Move package.json
        run: |
          chmod 777 ./dist/
          cp ./package.json ./dist/package.json
          cd ./dist/
      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
